### ISSUE TITLE
Help extracting and Editing Texture files

### ISSUE THREAD

**Issue by Nichenstein** [Wulf2k/DeS-BNDBuild#15]
Is it possible to extract and edit TPF files? When trying to edit Chr im getting an error of a missing txt file

[BLUS30443]\PS3_GAME\USRDIR\chr\c1020\c1020.chrbnd.extract\DemonsSoul\data\DVDROOT\chr\c1020\c1020.tpf.extract\filelist.txt'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at DesBNDBuild.Des_BNDBuild.Extract()

Could you please help me?

**Comment by AtilioA** [comment]
Use [Horkrux's fork](https://github.com/horkrux/DeS-BNDBuild)

**Comment by AtilioA** [comment]
Use [Horkrux's fork](https://github.com/horkrux/DeS-BNDBuild) as it is better at this point for Demon's Souls files.
